version: '3.3'
services:
  db:  #服务名，说明用途，创建容器，网络主机名
    build: ./xx-db/
    restart: always     #容器出问题自动退出了，docker自动启动一个新容器
    environment:
      MYSQL_ROOT_PASSWOR: root  #e.g.这个是mysql镜像的环境变量
  app:
    build: ./xxx-app/
    depends_on:
      - db   #依赖上面的db容器,docker自动给两个容器设置互联互通
    ports:
      - "80:80"
    restart: always